name: "🚀 Pull Request"
description: "새로운 기능 추가, 버그 수정 또는 기타 변경 사항을 설명해주세요."
title: "[PR] "
labels: ["pull request"]
body:
  - type: checkboxes
    id: pr_type
    attributes:
      label: "📝 What type of PR is this?"
      description: "PR의 유형을 선택해주세요."
      options:
        - label: "✨ New Features"
          required: false
        - label: "🐛 Bug Fix"
          required: false
        - label: "🛠️ Refactoring"
          required: false
        - label: "📝 Documentation Update"
          required: false
        - label: "🚀 Performance Improvement"
          required: false
        - label: "⚡ ETC (please write something below)"
          required: false

  - type: textarea
    id: description
    attributes:
      label: "💡 Description"
      description: "이 PR에서 변경된 내용을 설명해주세요."
      placeholder: "예: 로그인 기능 추가, API 응답 속도 개선 등"
    validations:
      required: true

  - type: textarea
    id: screenshot
    attributes:
      label: "📸 Screenshot"
      description: "변경 사항을 보여주는 스크린샷을 첨부해주세요. (선택 사항)"
      placeholder: "스크린샷이 있다면 여기에 추가하세요."

  - type: textarea
    id: reference
    attributes:
      label: "🔗 Reference"
      description: "참고할 만한 자료, 이슈 또는 관련 PR을 연결해주세요."
      placeholder: "예: #123, 관련 API 문서 링크"
